
INDIAN_STATES = [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    # Union Territories
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Jammu and Kashmir",
    "Ladakh",
    "Lakshadweep",
    "Puducherry",

]


INDIA_STATES_CITIES = {
    "Andhra Pradesh": ["Andhra Pradesh",
        "Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool",
        "Rajahmundry", "Tirupati", "Kakinada", "Kadapa", "Anantapur",
        "Vizianagaram", "Eluru", "Ongole", "Nandyal", "Machilipatnam",
        "Adoni", "Tenali", "Proddatur", "Chittoor", "Hindupur",
        "Bhimavaram", "Madanapalle", "Guntakal", "Dharmavaram", "Gudivada",
        "Narasaraopet", "Tadipatri", "Mangalagiri", "Chilakaluripet", "Amaravati"
    ],
    "Arunachal Pradesh": ["Arunachal Pradesh",
        "Itanagar", "Naharlagun", "Pasighat", "Namsai", "Bomdila",
        "Tezpur", "Ziro", "Along", "Tezu", "Khonsa",
        "Roing", "Aalo", "Changlang", "Seppa", "Daporijo"
    ],
    "Assam": [ "Assam",
        "Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon",
        "Tinsukia", "Tezpur", "Bongaigaon", "Dhubri", "Diphu",
        "North Lakhimpur", "Sivasagar", "Goalpara", "Barpeta", "Karimganj",
        "Haflong", "Mangaldoi", "Sibsagar", "Hojai", "Golaghat",
        "Kokrajhar", "Dhemaji", "Lakhimpur", "Nalbari", "Hailakandi"
    ],
    "Bihar": ["Bihar",
        "Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Purnia",
        "Darbhanga", "Bihar Sharif", "Arrah", "Begusarai", "Katihar",
        "Munger", "Chapra", "Hajipur", "Supaul", "Sasaram",
        "Dehri", "Siwan", "Motihari", "Nawada", "Bagaha",
        "Buxar", "Kishanganj", "Sitamarhi", "Jamalpur", "Jehanabad",
        "Aurangabad", "Bettiah", "Saharsa", "Madhubani", "Samastipur"
    ],
    "Chhattisgarh": [ "Chhattisgarh",
        "Raipur", "Bhilai", "Korba", "Bilaspur", "Durg",
        "Rajnandgaon", "Jagdalpur", "Raigarh", "Ambikapur", "Mahasamund",
        "Dhamtari", "Chirmiri", "Bhatapara", "Dongargarh", "Kawardha",
        "Tilda", "Mungeli", "Kondagaon", "Kanker", "Dantewada"
    ],
    "Goa": ["Goa",
        "Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda",
        "Bicholim", "Curchorem", "Sanquelim", "Cuncolim", "Valpoi",
        "Pernem", "Quepem", "Sanguem", "Canacona", "Mormugao"
    ],
    "Gujarat": ["Gujarat",
        "Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar",
        "Jamnagar", "Junagadh", "Gandhinagar", "Anand", "Navsari",
        "Morbi", "Mehsana", "Surendranagar", "Bharuch", "Porbandar",
        "Amreli", "Kheda", "Patan", "Godhra", "Dahod",
        "Valsad", "Botad", "Chhota Udaipur", "Dwarka", "Gir Somnath",
        "Kutch", "Mahisagar", "Narmada", "Sabarkantha", "Tapi"
    ],
    "Haryana": ["Haryana",
        "Faridabad", "Gurugram", "Panipat", "Ambala", "Yamunanagar",
        "Rohtak", "Hisar", "Karnal", "Sonipat", "Panchkula",
        "Bhiwani", "Sirsa", "Bahadurgarh", "Jind", "Thanesar",
        "Kaithal", "Rewari", "Palwal", "Narnaul", "Fatehabad",
        "Mewat", "Jhajjar", "Mahendragarh", "Charkhi Dadri", "Nuh"
    ],
    "Himachal Pradesh": ["Himachal Pradesh",
        "Shimla", "Manali", "Dharamsala", "Solan", "Mandi",
        "Palampur", "Baddi", "Nahan", "Kullu", "Hamirpur",
        "Una", "Chamba", "Bilaspur", "Keylong", "Reckong Peo",
        "Rampur", "Sundarnagar", "Parwanoo", "Nurpur", "Kangra"
    ],
    "Jharkhand": [ "Jharkhand",
        "Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Deoghar",
        "Phusro", "Hazaribagh", "Giridih", "Ramgarh", "Medininagar",
        "Chirkunda", "Chaibasa", "Dumka", "Godda", "Gumla",
        "Lohardaga", "Pakur", "Simdega", "Sahibganj", "Koderma"
    ],
    "Karnataka": ["Karnataka",
        "Bengaluru", "Mysuru", "Hubballi", "Mangaluru", "Belagavi",
        "Davanagere", "Ballari", "Vijayapura", "Shivamogga", "Tumakuru",
        "Raichur", "Bidar", "Kalaburagi", "Hassan", "Udupi",
        "Mandya", "Chikkamagaluru", "Dharwad", "Gadag", "Koppal",
        "Bagalkot", "Chitradurga", "Kolar", "Chamrajnagar", "Yadgir",
        "Haveri", "Kodagu", "Chikkaballapur", "Ramanagara", "Bengaluru Rural"
    ],
    "Kerala": ["Kerala",
        "Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam",
        "Palakkad", "Alappuzha", "Malappuram", "Kannur", "Kottayam",
        "Kasaragod", "Idukki", "Wayanad", "Pathanamthitta", "Ernakulam",
        "Munnar", "Thalassery", "Ponnani", "Chalakudy", "Guruvayur",
        "Kayamkulam", "Thiruvalla", "Vatakara", "Kanhangad", "Manjeri"
    ],
    "Madhya Pradesh": ["Madhya Pradesh",
        "Bhopal", "Indore", "Jabalpur", "Gwalior", "Ujjain",
        "Sagar", "Dewas", "Satna", "Ratlam", "Rewa",
        "Murwara", "Singrauli", "Burhanpur", "Khandwa", "Bhind",
        "Chhindwara", "Guna", "Shivpuri", "Vidisha", "Chhatarpur",
        "Damoh", "Mandsaur", "Khargone", "Neemuch", "Pithampur",
        "Niwari", "Harda", "Mandla", "Dindori", "Alirajpur"
    ],
    "Maharashtra": ["Maharashtra",
        "Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad",
        "Solapur", "Kalyan", "Thane", "Vasai", "Pimpri-Chinchwad",
        "Kolhapur", "Amravati", "Nanded", "Sangli", "Malegaon",
        "Jalgaon", "Akola", "Latur", "Ahmednagar", "Dhule",
        "Chandrapur", "Parbhani", "Ichalkaranji", "Jalna", "Ambarnath",
        "Bhiwandi", "Shirdi", "Satara", "Ratnagiri", "Wardha",
        "Gondia", "Beed", "Osmanabad", "Hingoli", "Washim",
        "Yavatmal", "Buldhana", "Nandurbar", "Gadchiroli", "Sindhudurg"
    ],
    "Manipur": ["Manipur",
        "Imphal", "Thoubal", "Bishnupur", "Churachandpur", "Senapati",
        "Ukhrul", "Chandel", "Jiribam", "Moreh", "Kakching",
        "Kangpokpi", "Noney", "Pherzawl", "Tamenglong", "Tengnoupal"
    ],
    "Meghalaya": [ "Meghalaya",
        "Shillong", "Tura", "Jowai", "Nongstoin", "Williamnagar",
        "Baghmara", "Resubelpara", "Nongpoh", "Mairang", "Mawkyrwat",
        "Ampati", "Khliehriat", "Mawsynram", "Cherrapunji", "Dawki"
    ],
    "Mizoram": ["Mizoram",
        "Aizawl", "Lunglei", "Champhai", "Saiha", "Kolasib",
        "Serchhip", "Lawngtlai", "Mamit", "Saitual", "Khawzawl",
        "Hnahthial", "Siaha", "Tlabung", "Bairabi", "Zawlnuam"
    ],
    "Nagaland": ["Nagaland",
        "Kohima", "Dimapur", "Mokokchung", "Tuensang", "Wokha",
        "Zunheboto", "Phek", "Mon", "Kiphire", "Longleng",
        "Peren", "Noklak", "Tseminyu", "Chumukedima", "Jalukie"
    ],
    "Odisha": ["Odisha",
        "Bhubaneswar", "Cuttack", "Rourkela", "Berhampur", "Sambalpur",
        "Puri", "Balasore", "Bhadrak", "Baripada", "Jharsuguda",
        "Jeypore", "Angul", "Barbil", "Kendujhar", "Sundargarh",
        "Koraput", "Phulbani", "Rayagada", "Bolangir", "Dhenkanal",
        "Kendrapara", "Jagatsinghpur", "Paradip", "Bhawanipatna", "Titlagarh"
    ],
    "Punjab": ["Punjab",
        "Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda",
        "Mohali", "Pathankot", "Hoshiarpur", "Batala", "Moga",
        "Firozpur", "Fatehgarh Sahib", "Muktsar", "Barnala", "Mansa",
        "Sangrur", "Fazilka", "Gurdaspur", "Ropar", "Nawanshahr",
        "Kapurthala", "Tarn Taran", "Rupnagar", "Malerkotla", "Zirakpur"
    ],
    "Rajasthan": ["Rajasthan",
        "Jaipur", "Jodhpur", "Kota", "Bikaner", "Ajmer",
        "Udaipur", "Bhilwara", "Alwar", "Bharatpur", "Sikar",
        "Pali", "Sri Ganganagar", "Tonk", "Nagaur", "Chittorgarh",
        "Jhalawar", "Jhunjhunu", "Barmer", "Sawai Madhopur", "Dungarpur",
        "Hanumangarh", "Banswara", "Dausa", "Jaisalmer", "Bundi",
        "Rajsamand", "Baran", "Karauli", "Sirohi", "Dholpur"
    ],
    "Sikkim": ["Sikkim",
        "Gangtok", "Namchi", "Mangan", "Gyalshing", "Rangpo",
        "Singtam", "Jorethang", "Nayabazar", "Ravangla", "Pelling",
        "Lachung", "Lachen", "Yuksom", "Soreng", "Pakyong"
    ],
    "Tamil Nadu": ["Tamil Nadu",
        "Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem",
        "Tirunelveli", "Tiruppur", "Vellore", "Erode", "Thoothukkudi",
        "Dindigul", "Thanjavur", "Ranipet", "Sivakasi", "Karur",
        "Udhagamandalam", "Hosur", "Nagercoil", "Kanchipuram", "Kumarapalayam",
        "Karaikkudi", "Neyveli", "Cuddalore", "Kumbakonam", "Tiruvannamalai",
        "Pollachi", "Rajapalayam", "Gudiyatham", "Pudukkottai", "Dharmapuri"
    ],
    "Telangana": ["Telangana",
        "Hyderabad", "Warangal", "Nizamabad", "Khammam", "Karimnagar",
        "Ramagundam", "Mahbubnagar", "Nalgonda", "Adilabad", "Suryapet",
        "Miryalaguda", "Siddipet", "Mancherial", "Jagtial", "Jangaon",
        "Vikarabad", "Wanaparthy", "Kothagudem", "Bhongir", "Medak",
        "Nagarkurnool", "Sangareddy", "Yadadri", "Kamareddy", "Nirmal"
    ],
    "Tripura": ["Tripura",
        "Agartala", "Udaipur", "Dharmanagar", "Pratapgarh", "Kailasahar",
        "Belonia", "Khowai", "Ambassa", "Sabroom", "Sonamura",
        "Amarpur", "Bishalgarh", "Melaghar", "Kumarghat", "Kamalpur"
    ],
    "Uttar Pradesh": ["Uttar Pradesh",
        "Lucknow", "Kanpur", "Ghaziabad", "Agra", "Meerut",
        "Varanasi", "Prayagraj", "Bareilly", "Aligarh", "Moradabad",
        "Saharanpur", "Gorakhpur", "Noida", "Firozabad", "Loni",
        "Jhansi", "Muzaffarnagar", "Mathura", "Rampur", "Shahjahanpur",
        "Farrukhabad", "Mau", "Hapur", "Etawah", "Mirzapur",
        "Bulandshahr", "Sambhal", "Amroha", "Hardoi", "Fatehpur",
        "Raebareli", "Orai", "Sitapur", "Bahraich", "Modinagar",
        "Unnao", "Jaunpur", "Lakhimpur", "Hathras", "Banda",
        "Pilibhit", "Barabanki", "Khurja", "Gonda", "Mainpuri",
        "Lalitpur", "Etah", "Deoria", "Bijnor", "Azamgarh"
    ],
    "Uttarakhand": ["Uttarakhand",
        "Dehradun", "Haridwar", "Roorkee", "Haldwani", "Rudrapur",
        "Kashipur", "Rishikesh", "Pithoragarh", "Ramnagar", "Almora",
        "Tehri", "Mussoorie", "Kotdwar", "Lansdowne", "Bageshwar",
        "Chamoli", "Champawat", "Nainital", "Pauri", "Uttarkashi"
    ],
    "West Bengal": ["West Bengal",
        "Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri",
        "Maheshtala", "Rajpur Sonarpur", "South Dumdum", "Bardhaman",
        "Malda", "Barasat", "Krishnanagar", "North Dumdum", "English Bazar",
        "Bankura", "Habra", "Jalpaiguri", "Kharagpur", "Bally",
        "Garulia", "Medinipur", "Haldia", "Raiganj", "Cooch Behar",
        "Darjeeling", "Balurghat", "Santipur", "Alipurduar", "Purulia",
        "Murshidabad", "Birbhum", "Nadia", "Hooghly", "North 24 Parganas"
    ],

    # Union Territories
    "Andaman and Nicobar Islands": ["Andaman and Nicobar Islands",
        "Port Blair", "Car Nicobar", "Diglipur", "Mayabunder", "Rangat",
        "Havelock Island", "Neil Island", "Campbell Bay", "Kamorta", "Nancowry"
    ],
    "Chandigarh": ["Chandigarh",
        "Chandigarh"
    ],
    "Dadra and Nagar Haveli and Daman and Diu": [
        "Daman", "Diu", "Silvassa", "Amli", "Khanvel"
    ],
    "Delhi": ["Delhi",
        "New Delhi", "Dwarka", "Rohini", "Pitampura", "Janakpuri",
        "Saket", "Lajpat Nagar", "Karol Bagh", "Connaught Place", "Shahdara",
        "Narela", "Bawana", "Mundka", "Vikaspuri", "Uttam Nagar",
        "Patparganj", "Mayur Vihar", "Preet Vihar", "Vasant Kunj", "Mehrauli"
    ],
    "Jammu and Kashmir": ["Jammu and Kashmir",
        "Srinagar", "Jammu", "Anantnag", "Baramulla", "Sopore",
        "Kathua", "Udhampur", "Rajouri", "Poonch", "Pulwama",
        "Kupwara", "Budgam", "Ganderbal", "Bandipora", "Kulgam",
        "Shopian", "Doda", "Kishtwar", "Ramban", "Reasi"
    ],
    "Ladakh": ["Ladakh",
        "Leh", "Kargil", "Diskit", "Padum", "Drass",
        "Nubra", "Zanskar", "Khaltsi", "Sankoo", "Turtuk"
    ],
    "Lakshadweep": ["Lakshadweep",
        "Kavaratti", "Agatti", "Amini", "Andrott", "Minicoy",
        "Chetlat", "Kadmat", "Kalpeni", "Kiltan", "Bangaram"
    ],
    "Puducherry": ["Puducherry",
        "Puducherry", "Karaikal", "Mahe", "Yanam", "Oulgaret",
        "Villianur", "Ariyankuppam", "Mannadipet", "Bahour", "Nettapakkam"
    ],
}